# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY Program2_AndresLopezBormann.c PROGRAM2_FUNCTIONS.H ./

# Compile the C program
RUN gcc -o Program2_AndresLopezBormann Program2_AndresLopezBormann.c
# Set the command to run when the container starts
CMD ["./Program2_AndresLopezBormann"]